### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by jlsorak** [nmackey/accessible-nprogress#13]
The `eval` being used in https://github.com/nmackey/accessible-nprogress/blob/master/dist/accessible-nprogress.js can't be used in IE 11 and is causing a syntax error.

**Comment by nmackey** [comment]
Interesting, I will take a look when I get a chance.  Is there any other information that you can give me about your setup or usage?

**Comment by jlsorak** [comment]
Thanks, I was testing on Windows 10 IE 11. I'm installing the library from NPM rather than CDN in a Create-React-App (version 3), running node version 12.

**Comment by nmackey** [comment]
Apologies I didn't get back to this sooner, but it is working on IE11 now.  Sorry for the long delay.

**Comment by nmackey** [comment]
Fixed in https://github.com/nmackey/accessible-nprogress/releases/tag/v2.1.2
